### ISSUE TITLE
Inspiration page in settings is broken

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#10]
![simulator screen shot - iphone se - 2018-04-23 at 15 03 36](https://user-images.githubusercontent.com/6820226/39147428-87197980-4707-11e8-8b98-7209a5a19b95.png)

**Comment by Ross-Gibson** [comment]
I think we can remove this section from the app entirely. Also, we should remove the Image credit from the Settings page, and the image on the "Look juicy" page when you first launch the app.

**Comment by Ross-Gibson** [comment]
In progress. I will do this before releasing 4.1.4.
