### ISSUE TITLE
Remove the Cable Selector from the Onboarding flow

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#14]
Since the Triggertrap Mobile Kits are no longer available for purchase, we should not direct users to purchase a kit during the onboarding flow. However, we should still show the instructions of how to use the Mobile Kit, for those that do have one. Perhaps, we need to ask the user if they have a Mobile Kit during the onboarding and then show the instructions?

**Comment by alex-taffe** [comment]
Agreed, should we close #8 ? Seems to be a duplicate

**Comment by Ross-Gibson** [comment]
Sorry, I didn't realise that I'd duplicated the issue you created. We can close one of these. We should check the app for other references to the Triggertrap website too, I think there may be a link in the help menu.

**Comment by Ross-Gibson** [comment]
Closing this a s it's a duplicate of #8
