### ISSUE TITLE
Comply with GDPR

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#15]
We need to remove all instances of user data tracking, and add a privacy policy to the website associated with the App Store listing (http://rossjamesgibson.com).

We should remove all references to Mixpanel, and corresponding events. We should also make sure there is nowhere else within the app that we're tracking data.

**Comment by alex-taffe** [comment]
@Ross-Gibson do we need to have this finished before the App Store release?

**Comment by alex-taffe** [comment]
#16 fixes all tracking issues

**Comment by Ross-Gibson** [comment]
Thanks @alex-taffe. I uploaded a binary yesterday to iTC, and I'm now chatting with Apple support to get the app transferred. I will review this and we can ship it with the next release. GDPR goes into effect on May 25th, so we have plenty of time to ship another build.

**Comment by Ross-Gibson** [comment]
Checklist: https://gdprchecklist.io
