### ISSUE TITLE
when I use Xcode8.3.3,it can not open

### ISSUE THREAD

**Issue by zhoupIT** [Triggertrap/triggertrap-ios#2]

**Comment by zhoupIT** [comment]
Xcode 8 will not be able to build the project “Triggertrap”, and certain editing features will not function properly until the Swift source code in this project has been converted.

**Comment by Ross-Gibson** [comment]
I'm closing this issue since it was fixed by @alex-taffe.

@zhoupIT, please checkout the latest `develop` branch, and you should be able to build with Xcode 9.3.
