### ISSUE TITLE
Remove all UIAlertView’s

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#25]
UIAlertView was deprecated as of iOS 8. These should be replaced by UIAlertController

**Comment by Ross-Gibson** [comment]
Yep, this needs doing. If you're able to handle this @alex-taffe would be great. Thanks.

**Comment by alex-taffe** [comment]
Yep @Ross-Gibson

**Comment by alex-taffe** [comment]
Fixed by #30
