### ISSUE TITLE
Low volume notification is covered by iPhone X notch

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#26]
![img_6956](https://user-images.githubusercontent.com/6820226/40386112-caa74250-5dd6-11e8-9fb2-e2d47e14c17c.PNG)
![img_6956_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/6820226/40386106-c7fe7d48-5dd6-11e8-8e74-9f37bdc022c5.png)

**Comment by Ross-Gibson** [comment]
@alex-taffe I'd noticed this one too. Would be good to to a release after 4.1.4 to fix all of the iPhone X issues.

**Comment by alex-taffe** [comment]
I’ll get this one @Ross-Gibson

**Comment by alex-taffe** [comment]
Fixed by #41
