### ISSUE TITLE
Timelapse Pro Screen is glitchy

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#27]
![img_6957](https://user-images.githubusercontent.com/6820226/40386899-fe28de34-5dd8-11e8-9762-2e7dcb71828e.PNG)

The scrolling on this screen is glitchy and buttons are hidden

**Comment by alex-taffe** [comment]
Looks like 4b79ea3 resolved this @Ross-Gibson ?

**Comment by Ross-Gibson** [comment]
@alex-taffe yeah, I fixed this and a few other things that we didn't have issues for. I will push a release for 4.1.4 today. And then we can work on fixing all of the other issues in the next build. My main concern at the moment is GDPR.
