### ISSUE TITLE
TimeLapse Pro “Tell me more!” results in 404 error

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#28]
Tapping on “Tell me more!” on the time lapse pro screen results in a 404 error

**Comment by alex-taffe** [comment]
Looks like 4b79ea3d610bab74cb747f328cdd491e1c657f1a resolved this @Ross-Gibson ?

**Comment by Ross-Gibson** [comment]
@alex-taffe yeah, I fixed this by removing the button.
