### ISSUE TITLE
iPhone X - White padding at the bottom of the menu

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#31]
We should remove the padding but make sure that the button is still accessible.

![image-1-1](https://user-images.githubusercontent.com/1439601/40409543-2c663762-5e63-11e8-9979-f4ff3f5113aa.jpg)

**Comment by alex-taffe** [comment]
@Ross-Gibson I can take this one. Do you think we remove the padding at the top of the scroll (so buttons are being clipped by the home indicator) and then once someone gets to the end of the scroll view, have the white padding past the last button (as it appears now) so people can still get to the solar calculator?

**Comment by Ross-Gibson** [comment]
If you rather me do a design I can mock something up later this afternoon/evening.

**Comment by alex-taffe** [comment]
Fixed by #39
