### ISSUE TITLE
iPhone X - The keyboard is blocked by the home button

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#32]
@alex-taffe I think this one can be resolved by increasing the height of the bottom view on the iPhone X. Doing that should fix this everywhere. I'm happy to take this one.

![image-1-2](https://user-images.githubusercontent.com/1439601/40409610-5aa361e0-5e63-11e8-9ddf-7ce1200c9b0b.jpg)

**Comment by alex-taffe** [comment]
@Ross-Gibson do you want me to get this?

**Comment by alex-taffe** [comment]
Fixed by #66
