### ISSUE TITLE
Timelapse Pro "View in App Store" button is unbalanced

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#33]
- [ ] Fix the lagging around the button so that it appears balanced (This part may be iPhone X specific)
- [ ] Back the bottom view grey to match the design of the other screens
- [ ] Fix the rotation issues on the screen. If you rotate to landscape the button disappears

![image-1-3](https://user-images.githubusercontent.com/1439601/40409701-9b46fb12-5e63-11e8-9a0d-2eb7245638b4.jpg)

**Comment by alex-taffe** [comment]
I'll take this @Ross-Gibson
