### ISSUE TITLE
Solar Calculator - The sun does not sit on the line

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#35]
This may be iPhone X specific.

![image-1-5](https://user-images.githubusercontent.com/1439601/40409989-7e7b1710-5e64-11e8-8aaf-1902cdd3d5d6.jpg)

**Comment by alex-taffe** [comment]
I can get this

**Comment by alex-taffe** [comment]
![simulator screen shot - iPhone 8 plus - 2018-05-23 at 16 01 11](https://user-images.githubusercontent.com/6820226/40448108-8e36d00c-5ea2-11e8-9eb0-eb467458631f.png)
Occuring on all devices

**Comment by alex-taffe** [comment]
Fixed by #43
