### ISSUE TITLE
UI is clipped on motion sensor screen

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#5]
iPhone X, iOS 11.3, Triggertrap 4.1.2 build 926

![img_098dabc9ba49-1](https://user-images.githubusercontent.com/6820226/39146762-ab60282c-4705-11e8-96cb-7972a6f228d1.jpeg)

**Comment by alex-taffe** [comment]
Starting on this now

**Comment by alex-taffe** [comment]
Fixed by 357b40f9551017575ad809b155aa2642d4fedb83

**Comment by alex-taffe** [comment]
PR #21 created

**Comment by alex-taffe** [comment]
@Ross-Gibson wait so do you want me to fix this still?

**Comment by Ross-Gibson** [comment]
@alex-taffe no it's fine, I'm working on a branch to get the app ready for another release. I can fix this.
