### ISSUE TITLE
RPCircularProgress does not support Swift 4.2

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#59]
[RPCircularProgress](https://github.com/iwasrobbed/RPCircularProgress) does not support swift 4.2 currently and is causing the build to fail. I opened a [PR](https://github.com/iwasrobbed/RPCircularProgress/pull/33). Until this is fixed I created a [fork](https://github.com/alex-taffe/RPCircularProgress) that the Podfile is referencing. Once the PR is accepted, we should swap back to the official repo. Change made as of commit 5fe84be356402a888ec54f00a09f215711e96e0f. Blocked by iwasrobbed/RPCircularProgress#33

**Comment by Ross-Gibson** [comment]
Awesome, thanks @alex-taffe.
