### ISSUE TITLE
UI is clipped on peekaboo screen

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#6]
iPhone X, iOS 11.3, Triggertrap 4.1.2 build 926

![img_57fa60bbb99a-1](https://user-images.githubusercontent.com/6820226/39146824-de643ae2-4705-11e8-9b26-24ffad9ff9ba.jpeg)

**Comment by alex-taffe** [comment]
@Ross-Gibson I’m starting on this now

**Comment by alex-taffe** [comment]
Fixed by b8d4f8740b5a3176a20651cb6c3fb3138a1a4605

**Comment by alex-taffe** [comment]
PR #21 created

**Comment by alex-taffe** [comment]
@Ross-Gibson wait so do you want me to fix this still?

**Comment by Ross-Gibson** [comment]
@alex-taffe no it's fine, I'm working on a branch to get the app ready for another release. I can fix this.
