### ISSUE TITLE
UI does not rotate when the device is upside-down.

### ISSUE THREAD

**Issue by Ross-Gibson** [Triggertrap/triggertrap-ios#64]
When you rotate the device so that it's upside-down (notch at the bottom), the UI does not rotate. This effects all of the modes. See screenshots for SCR and Solar Calc.

![simulator screen shot - iphone xr - 2018-12-30 at 10 24 35](https://user-images.githubusercontent.com/1439601/50546299-5cadf500-0c1d-11e9-8fec-61f0e06d7675.png)
![simulator screen shot - iphone xr - 2018-12-30 at 10 24 52](https://user-images.githubusercontent.com/1439601/50546300-5d468b80-0c1d-11e9-88af-b3dab69776a0.png)

**Comment by alex-taffe** [comment]
Starting now

**Comment by alex-taffe** [comment]
@Ross-Gibson this isn’t fixable, per apple’s docs "For example, the UIInterfaceOrientation.portraitUpsideDown orientation is not supported on iPhone X.”

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations

**Comment by Ross-Gibson** [comment]
@alex-taffe thanks for taking a look. I'll close this.
