### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#71]
Getting the error "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value" on TimeWarpViewController.swift:167.

It seems the app doesn't actually have the image file "tickDown".

@Ross-Gibson do you happen to know what this file should be?

**Comment by alex-taffe** [comment]
![IMG_2259](https://user-images.githubusercontent.com/6820226/56080475-b783ea80-5dcf-11e9-94bc-7b361d454f4e.jpg)

<img width="545" alt="Screen Shot 2019-04-13 at 9 37 33 AM" src="https://user-images.githubusercontent.com/6820226/56080482-c4a0d980-5dcf-11e9-8619-ad7486cc7c5c.png">
So I played around with this and it appears to be the green space as shown in the first image. I put a placeholder there and it stopped the app from crashing. What I don't get is how this was never crashing before. It works on my phone with 4.1.7 (940) but 4.1.8 (941) with commit 52f3b237bfed009faa3e1eecb7adcb9a41194618 is crashing due to that image

I'm not even sure an image should be there based on the App Store screenshots

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe, yeah there should be an image there. It should be a down arrow, that then animates to point upwards when you pull down the view. Looking at that commit I'm not exactly sure what's going on!

I've just downloaded the App Store build for 4.1.8, and it's not crashing (for me), so I guess we have some time to fix this. I'll take a look at the history now to see if I can see anything.

**Comment by alex-taffe** [comment]
That's super weird that it's inconsistently crashing. I'm honestly not sure how the app ever runs without crashing considering the UIImage is being explicitly unwrapped and the image does not exist. I guess we just need to find that arrow image or replace it with something

**Comment by Ross-Gibson** [comment]
Yeah, it's weird. I've had another look and none of the images in the `TimeWarpController` appear to be in the Asset Catalogue, i.e. `timeWarpPreviewButton`, `timeWarpClockCircle`, `timeWarpClockCenter` etc.

I think the best thing to do is just to create a new asset and replace it. I can do that today.
