### ISSUE TITLE
Respect system dark mode toggle

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#78]
iOS 13 now has a system dark mode. Trigger trap should be able to respond to this new feature. On iOS 12 and before, the light/dark functionality should remain the same. On iOS 13 and up, the toggle should change to a segmented display with “System”, “Light”, and “Dark” being options. This would allow users to have the app respect their system settings or set different preferences for trigger trap alone. New installs of the app and old installs will both default to “System”. In addition, this knocks out #7 because the system can automatically toggle dark and light mode. @Ross-Gibson thoughts?

**Comment by alex-taffe** [comment]
Having investigated this more, it seems to make more sense to just remove the toggle when a user is on iOS 13 or above and always respect the system settings, as certain items like toggle switches aren’t appropriate when the system doesn’t match the app setting

**Comment by Ross-Gibson** [comment]
@alex-taffe all your suggestions here sound good to me.

**Comment by alex-taffe** [comment]
Fixed as of #80
