### ISSUE TITLE
Remove onboarding screens that reference the triggertrap website

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#8]
This screen should be changed to explain what Triggertrap was rather than directing people to the now defunct website

![simulator screen shot - iphone se - 2018-04-23 at 14 59 50](https://user-images.githubusercontent.com/6820226/39147211-0a328510-4707-11e8-8ff9-f2ddf8f3b801.png)

**Comment by Ross-Gibson** [comment]
In progress. I will do this before releasing 4.1.4.
