### ISSUE TITLE
Remove Cable Selector from settings page

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#9]
This should either be removed or changed to inform users what is compatible to with their cameras. The website no longer exists so the links dont really make sense

![simulator screen shot - iphone se - 2018-04-23 at 15 01 51](https://user-images.githubusercontent.com/6820226/39147308-44012e40-4707-11e8-9a19-de127d555fe6.png)
![simulator screen shot - iphone se - 2018-04-23 at 15 01 50](https://user-images.githubusercontent.com/6820226/39147309-440eda68-4707-11e8-9e29-f152be2ae8d1.png)

**Comment by Ross-Gibson** [comment]
In progress. I will do this before releasing 4.1.4.
